services:
  nginx:
    image: nginx:latest
    container_name: nginx_lara
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    user: '1000:1000'
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php-fpm_lara
    volumes:
      - ./:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_lara
    environment:
      PMA_HOST: mysql_lara
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_lara
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
